### ISSUE TITLE
Examples of how to create a custom Adapter

### ISSUE THREAD

**Issue by ty0002** [lowla/lowladb-node#1]
Am I right in thinking that I can do either of the following to set up my sync architecture… 
- A simple setup
  - Pull the lowladb-node repo and launch the express application in app.js
  - Consider the running Lowla instance as my entire app backend, which will use the default mongo-driven Datastore
  - Configure client applications to push/pull from that instance
- A custom adapter setup
  - Add lowladb-node as an npm dependency to my own express app
  - Setup instances of LowlaSync and LowlaAdapter in my own app.js. similar to how you've set them up [here](https://github.com/lowla/lowladb-node/blob/master/app.js#L11-L21) and [here](https://github.com/lowla/lowladb-node/blob/master/app.js#L53-L54)
  - Define and inject my own custom Datastore class into LowlaAdapter
    - I would define a class that exposes the same interface as [this one](https://github.com/lowla/lowladb-node/blob/master/lib/datastore/datastore.js)
    - For example, I might define a MysqlDatastore that implements `updateDocumentByOperations`, `removeDocument`, `findInCollection` etc
  - Configure client applications to push/pull from my own running node server that now has sync capability

Or should I be using it differently? Are there any docs or examples?

**Comment by adnamsale** [comment]
Hi Steve,

Just following up on our email conversation, you're quite correct that there will be a simple setup if you just want to sync all data with a clean MongoDB instance and a custom adapter setup. We're still working on the interface(s) to custom adapters. At the lowest level, we will document the http-based protocol that the client, syncer and adapter use to communicate so that you can write a completely custom adapter. If, say, you're a pure Microsoft shop then that'll allow you to write an adapter without needing to go anywhere near node.js programming. 

We may additionally restructure the node.js adapter a little to make it possible to plug in a new Datastore. That will give you a quick start on a custom adapter if you're comfortable in node.js. In that case we would of course document the syntax and semantics of the API.

So the approach you describe is exactly what we're planning but we're just a couple of months away.

Mark

**Comment by ghost** [comment]
Thanks for you response - look forward to seeing the http protocol spec.
